jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Debug files
        run: ls -al
        # Check if package.json is in the right place and what's inside
        run: cat package.json

      - name: Run tests
        run: npm test
